### ISSUE TITLE
Game Gear stereo test

### ISSUE THREAD

**Issue by ebourg** [sverx/SMSTestSuite#1]
The Game Gear supports stereo sound, natively through the headphone, and nowadays on modded consoles with two speakers. Would it be possible to enhance the audio test to balance the channels on the left/right sides.

https://www.smspower.org/Development/GameGearStereo

**Comment by sverx** [comment]
It's not possible to select L/R audio channels in SMS mode, so the SMS Test Suite won't be able to test that.

You might want to look into [GGTestSuite](https://github.com/sverx/GGTestSuite) which runs in GameGear native mode... there's a beta (v. 0.12) released [here](https://www.smspower.org/forums/17116-SMSTestSuiteWorkInProgressHomebrew?start=200#119324) at the end of the page.

Let me know if that works well enough :smile:

**Comment by ebourg** [comment]
Nice, thank you for the pointer, I'll give it a try.
